# Example 3
# Amorphous ice, minimal logging, Europa-style parallel particle run.
# Runs one monoenergetic batch in one macro:
#   0.5 MeV
# with 100 primaries and cosine angular distribution.

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/run/numberOfThreads 10
/dna/test/setLogMode minimal
/dna/test/setIceSize 100 100 100 mm
/dna/test/setMatDens G4_WATER_ICE_USER 0.94 g/cm3
/dna/test/setMat G4_WATER_ICE_USER

/run/initialize

/gps/particle e-
/gps/number 1
/gps/pos/type Point
/gps/pos/centre 0 0 -0.001 mm
/gps/ang/type cos
/gps/ang/mintheta 0 deg
/gps/ang/minphi 0 deg
/gps/ang/maxphi 360 deg
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 -1 0
/dna/test/setMaxTheta true
/gps/ene/type Mono

/gps/ene/mono 0.5 MeV
/run/beamOn 100
